version: "3.2"

services:
  
  php:
    build: 
      context: .
      dockerfile: './.docker/php/Dockerfile' 
      args:
        UID: ${UID}
        GID: ${GID}
    networks:
      - backend
    volumes:
      - ./container/config:/var/www/html/config
      - ./container/templates:/var/www/html/templates
      - ./container/modules:/var/www/html/modules
      - ./container/web:/var/www/html/web
      - ./container/composer.json:/var/www/html/composer.json
      - ./container/.env:/var/www/html/.env

  apache:
    build: 
      context: .
      dockerfile: './.docker/apache/Dockerfile'
    depends_on:
      - php
      - db
    networks:
      - frontend
      - backend
    ports:
      - "8080:80"
    volumes:
      - ./container/web:/var/www/html/web

  # nginx:
  #     build:
  #       context: .
  #       dockerfile: ./.docker/nginx/Dockerfile
  #     depends_on:
  #       - php
  #       - db
  #     networks:
  #       - frontend
  #       - backend
  #     ports:
  #       - 8080:80
  #     volumes:
  #       - ./container/web:/var/www/html/web

  # mysql:
  #   image: mysql:5.7
  #   command: --default-authentication-plugin=mysql_native_password
  #   restart: always
  #   networks:
  #     - backend
  #   environment:
  #     - MYSQL_ROOT_PASSWORD=rootpassword
  #     - MYSQL_DATABASE=craftcms
  #     - MYSQL_USER=craft
  #     - MYSQL_PASSWORD=craftcms
  #   volumes:
  #     - db:/var/lib/mysql

  db:
    image: mariadb:10.3
    volumes:
      - db:/var/lib/db
    networks:
      - backend
    ports:
      - 33060:3306
    environment:
      MYSQL_ROOT_PASSWORD: y=cpz9hvk.dYCdmHu+(zM9t6
      MYSQL_DATABASE: craft
      MYSQL_USER: craft
      MYSQL_PASSWORD: craft

  # phpmyadmin:
  #   image: phpmyadmin/phpmyadmin
  #   depends_on :
  #      - db
  #   networks: 
  #     - backend
  #   external_links:
  #     - db:db
  #   ports:
  #     - 8181:80
  #   environment:
  #     MYSQL_USERNAME: root
  #     MYSQL_ROOT_PASSWORD: rootpassword

networks:
  frontend:
  backend:

volumes:
  db: