version: "3.2"

services:
  php:
    build: 
      context: .
      dockerfile: './.docker/php/Dockerfile' 
      args:
        UID: ${UID}
        GID: ${GID}
    networks:
      - backend
    volumes:
      - ./container/config:/var/www/html/config
      - ./container/templates:/var/www/html/templates
      - ./container/modules:/var/www/html/modules
      - ./container/web:/var/www/html/web
      - ./container/composer.json:/var/www/html/composer.json
      - ./container/.env:/var/www/html/.env

  webserver:
    build: 
      context: .
      dockerfile: './.docker/apache/Dockerfile'
    env_file:
      './.docker/apache/.env'
    environment:
      - DOCUMENT_ROOT=/var/www/html/web
      - SERVER_NAME=www.talleys.local
      - SERVER_ALIAS=talleys.local
    depends_on:
      - php
      - database
    networks:
      - frontend
      - backend
    ports:
      - 80:80
    volumes:
      - ./container/web:/var/www/html/web

  database:
    image: mariadb:10.3
    env_file:
      './.docker/mariadb/.env'
    volumes:
      - database:/var/lib/mysql
    networks:
      - backend
    ports:
      - 3306:3306

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    depends_on :
       - database
    networks: 
      - backend
    external_links:
      - db:database
    ports:
      - 8181:80
    environment:
      MYSQL_USERNAME: root
      MYSQL_ROOT_PASSWORD: rootpassword

networks:
  frontend:
  backend:

volumes:
  database: